const express = require("express");
const cors = require('cors');


const app = express();
app.use(cors());

// Define an array of data objects with ids
const data = [
  {id:1,
    
      quote: {
        lineItemGroups: [
          {
            delveryAddress: {
              zipCode: 84115,
              state: "UT",
              city: "South Salt Lake",
              street: "3244 S 300 W",
            },
            subtotal: 17318.7,
            order: 1,
            name: "Group1",
            id: "a0p4U00000FC5xnQAD",
          },
          {
            deliveryAddress: {
              zipCode: "69696",
              state: "UT",
              city: "South Salt Lake",
              street: "3244 South 300 West",
            },
            subtotal: 0,
            order: 2,
            name: "Payoffs and Pickup Equipment",
            id: "a0p4U00000FC8CEQA1",
          },
        ],
        lineItems: [
          {
            declinedQuantity: null,
            isRejected: false,
            locationRemarks: null,
            optionType: null,
            rollChildQtyToParent: false,
            showOnQuote: true,
            additionalDiscount: 0,
            totalProvidedCopies: 0,
            monthlyVolume: null,
            perPageOverageRate: null,
            selectedPerPageRate: 0,
            customPerPageRate: null,
            productCode: "BP-50C31",
            productServiceType: null,
            isServiceProduct: false,
            leasePrice: 229.46,
            salesPrice: 9890.55,
            listPrice: 3296.85,
            order: 1,
            lineDetail: "Lease Rate Used: .0232",
            lineDetailForGP: "Lease Rate Used: .0232",
            description:
              "31 pages-per-minute Color Sharp Multi-function System",
            hidden: false,
            name: "BP-50C31 - Sharp Color Copier #",
            picture: null,
            quantity: 3,
            parentId: null,
            groupId: "a0p4U00000FC5xnQAD",
            id: "a0q4U00000PozQnQAJ",
          },
          {
            declinedQuantity: null,
            isRejected: false,
            locationRemarks: null,
            optionType: "Component",
            rollChildQtyToParent: false,
            showOnQuote: true,
            additionalDiscount: 0,
            totalProvidedCopies: 0,
            monthlyVolume: null,
            perPageOverageRate: null,
            selectedPerPageRate: 0,
            customPerPageRate: null,
            productCode: "BP-DE12",
            productServiceType: null,
            isServiceProduct: false,
            leasePrice: 35.97,
            salesPrice: 1550.25,
            listPrice: 516.75,
            order: 2,
            lineDetail: "Lease Rate Used: .0232",
            lineDetailForGP: "Lease Rate Used: .0232",
            description: "Stand/1 X 500 Paper Feed Desk Unit",
            hidden: false,
            name: "BP-DE12 - Stand/1 X 550 Paper Deck (50C26-70M65)#",
            picture: null,
            quantity: 3,
            parentId: "a0q4U00000PozQnQAJ",
            groupId: "a0p4U00000FC5xnQAD",
            id: "a0q4U00000PozQoQAJ",
          },
          {
            declinedQuantity: null,
            isRejected: false,
            locationRemarks: null,
            optionType: "Component",
            rollChildQtyToParent: false,
            showOnQuote: true,
            additionalDiscount: 0,
            totalProvidedCopies: 0,
            monthlyVolume: null,
            perPageOverageRate: null,
            selectedPerPageRate: 0,
            customPerPageRate: null,
            productCode: "BP-FN11",
            productServiceType: null,
            isServiceProduct: false,
            leasePrice: 81.52,
            salesPrice: 3513.9,
            listPrice: 1171.3,
            order: 3,
            lineDetail: "Lease Rate Used: .0232",
            lineDetailForGP: "Lease Rate Used: .0232",
            description: "Sharp Finisher (50C26-70C45) #",
            hidden: false,
            name: "BP-FN11 - Finisher (50C26-70M55) #",
            picture: null,
            quantity: 3,
            parentId: "a0q4U00000PozQnQAJ",
            groupId: "a0p4U00000FC5xnQAD",
            id: "a0q4U00000PozQpQAJ",
          },
          {
            declinedQuantity: null,
            isRejected: false,
            locationRemarks: null,
            optionType: "Component",
            rollChildQtyToParent: false,
            showOnQuote: false,
            additionalDiscount: 0,
            totalProvidedCopies: 0,
            monthlyVolume: null,
            perPageOverageRate: null,
            selectedPerPageRate: 0,
            customPerPageRate: null,
            productCode: "Sharp 90 Day Warranty",
            productServiceType: "Warranty",
            isServiceProduct: false,
            leasePrice: 0,
            salesPrice: 0,
            listPrice: 0,
            order: 4,
            lineDetail:
              "CPP: 0 (Retail)<br>Overage Rate 0<br>Pages: 0<br>Lease Rate Used: .0232<br>",
            lineDetailForGP: "CPP: 0 (Retail) Pages: 0 Lease Rate Used: .0232",
            description: "Sharp Manufacturer Warranty",
            hidden: false,
            name: "Sharp 90 Day Warranty",
            picture: null,
            quantity: 3,
            parentId: "a0q4U00000PozQnQAJ",
            groupId: "a0p4U00000FC5xnQAD",
            id: "a0q4U00000PozQqQAJ",
          },
          {
            declinedQuantity: null,
            isRejected: false,
            locationRemarks: null,
            optionType: "Component",
            rollChildQtyToParent: false,
            showOnQuote: true,
            additionalDiscount: 0,
            totalProvidedCopies: 0,
            monthlyVolume: null,
            perPageOverageRate: null,
            selectedPerPageRate: 0,
            customPerPageRate: null,
            productCode: "Atlas/Titan Startup Bundle NASPO",
            productServiceType: null,
            isServiceProduct: false,
            leasePrice: 33.48,
            salesPrice: 1443,
            listPrice: 481,
            order: 5,
            lineDetail: null,
            lineDetailForGP: null,
            description: "Atlas/Titan Startup Bundle NASPO",
            hidden: false,
            name: "Atlas/Titan Startup Bundle NASPO",
            picture: null,
            quantity: 3,
            parentId: "a0q4U00000PozQnQAJ",
            groupId: "a0p4U00000FC5xnQAD",
            id: "a0q4U00000PozQrQAJ",
            services: [],
            isLastWithParent: true,
          },
          {
            declinedQuantity: null,
            isRejected: false,
            locationRemarks: null,
            optionType: "Component",
            rollChildQtyToParent: false,
            showOnQuote: false,
            additionalDiscount: 0,
            totalProvidedCopies: 0,
            monthlyVolume: null,
            perPageOverageRate: null,
            selectedPerPageRate: 0,
            customPerPageRate: null,
            productCode: "BP-NT70BA",
            productServiceType: null,
            isServiceProduct: false,
            leasePrice: 0,
            salesPrice: 0,
            listPrice: 0,
            order: 6,
            lineDetail: null,
            lineDetailForGP: null,
            description: "Sharp Toner - Black",
            hidden: false,
            name: "Sharp Toner - Black",
            picture: null,
            quantity: 3,
            parentId: "a0q4U00000PozQrQAJ",
            groupId: "a0p4U00000FC5xnQAD",
            id: "a0q4U00000PozQsQAJ",
          },
          {
            declinedQuantity: null,
            isRejected: false,
            locationRemarks: null,
            optionType: "Component",
            rollChildQtyToParent: false,
            showOnQuote: false,
            additionalDiscount: 0,
            totalProvidedCopies: 0,
            monthlyVolume: null,
            perPageOverageRate: null,
            selectedPerPageRate: 0,
            customPerPageRate: null,
            productCode: "BP-NT70CA",
            productServiceType: null,
            isServiceProduct: false,
            leasePrice: 0,
            salesPrice: 0,
            listPrice: 0,
            order: 7,
            lineDetail: null,
            lineDetailForGP: null,
            description: "Sharp Toner - Cyan",
            hidden: false,
            name: "Sharp Toner - Cyan",
            picture: null,
            quantity: 3,
            parentId: "a0q4U00000PozQrQAJ",
            groupId: "a0p4U00000FC5xnQAD",
            id: "a0q4U00000PozQtQAJ",
          },
          {
            declinedQuantity: null,
            isRejected: false,
            locationRemarks: null,
            optionType: "Component",
            rollChildQtyToParent: false,
            showOnQuote: false,
            additionalDiscount: 0,
            totalProvidedCopies: 0,
            monthlyVolume: null,
            perPageOverageRate: null,
            selectedPerPageRate: 0,
            customPerPageRate: null,
            productCode: "BP-NT70MA",
            productServiceType: null,
            isServiceProduct: false,
            leasePrice: 0,
            salesPrice: 0,
            listPrice: 0,
            order: 8,
            lineDetail: null,
            lineDetailForGP: null,
            description: "Sharp Toner - Magenta",
            hidden: false,
            name: "Sharp Toner - Magenta",
            picture: null,
            quantity: 3,
            parentId: "a0q4U00000PozQrQAJ",
            groupId: "a0p4U00000FC5xnQAD",
            id: "a0q4U00000PozQuQAJ",
          },
          {
            declinedQuantity: null,
            isRejected: false,
            locationRemarks: null,
            optionType: "Component",
            rollChildQtyToParent: false,
            showOnQuote: false,
            additionalDiscount: 0,
            totalProvidedCopies: 0,
            monthlyVolume: null,
            perPageOverageRate: null,
            selectedPerPageRate: 0,
            customPerPageRate: null,
            productCode: "BP-NT70YA",
            productServiceType: null,
            isServiceProduct: false,
            leasePrice: 0,
            salesPrice: 0,
            listPrice: 0,
            order: 9,
            lineDetail: null,
            lineDetailForGP: null,
            description: "Sharp Toner - Yellow",
            hidden: false,
            name: "Sharp Toner - Yellow",
            picture: null,
            quantity: 3,
            parentId: "a0q4U00000PozQrQAJ",
            groupId: "a0p4U00000FC5xnQAD",
            id: "a0q4U00000PozQvQAJ",
          },
          {
            declinedQuantity: null,
            isRejected: false,
            locationRemarks: null,
            optionType: "Component",
            rollChildQtyToParent: false,
            showOnQuote: true,
            additionalDiscount: 0,
            totalProvidedCopies: 0,
            monthlyVolume: null,
            perPageOverageRate: null,
            selectedPerPageRate: 0,
            customPerPageRate: null,
            productCode: "SURGE-15",
            productServiceType: null,
            isServiceProduct: false,
            leasePrice: 8.14,
            salesPrice: 351,
            listPrice: 117,
            order: 10,
            lineDetail: null,
            lineDetailForGP: null,
            description: "15 Amp Surge Suppressor",
            hidden: false,
            name: "15 Amp Surge Suppressor",
            picture: null,
            quantity: 3,
            parentId: "a0q4U00000PozQrQAJ",
            groupId: "a0p4U00000FC5xnQAD",
            id: "a0q4U00000PozQwQAJ",
          },
          {
            declinedQuantity: null,
            isRejected: false,
            locationRemarks: null,
            optionType: "Component",
            rollChildQtyToParent: false,
            showOnQuote: true,
            additionalDiscount: 0,
            totalProvidedCopies: 0,
            monthlyVolume: null,
            perPageOverageRate: null,
            selectedPerPageRate: 0,
            customPerPageRate: null,
            productCode: "ITOM",
            productServiceType: null,
            isServiceProduct: false,
            leasePrice: 13.22,
            salesPrice: 570,
            listPrice: 95,
            order: 11,
            lineDetail: null,
            lineDetailForGP: null,
            description:
              "IT Open Market on-Site Network Installation (2 Hours)",
            hidden: false,
            name: "IT Open Market",
            picture: null,
            quantity: 6,
            parentId: "a0q4U00000PozQrQAJ",
            groupId: "a0p4U00000FC5xnQAD",
            id: "a0q4U00000PozQxQAJ",
          },
          {
            declinedQuantity: null,
            isRejected: false,
            locationRemarks: null,
            optionType: null,
            rollChildQtyToParent: false,
            showOnQuote: false,
            additionalDiscount: 0,
            totalProvidedCopies: 0,
            monthlyVolume: null,
            perPageOverageRate: null,
            selectedPerPageRate: 0,
            customPerPageRate: null,
            productCode: "Existing Equipment",
            productServiceType: null,
            isServiceProduct: false,
            leasePrice: 0,
            salesPrice: 0,
            listPrice: 0,
            order: 12,
            lineDetail: null,
            lineDetailForGP: null,
            description: "Existing Equipment",
            hidden: false,
            name: "Existing Equipment",
            picture: null,
            quantity: 1,
            parentId: null,
            groupId: "a0p4U00000FC8CEQA1",
            id: "a0q4U00000PozQyQAJ",
          },
          {
            declinedQuantity: null,
            isRejected: false,
            locationRemarks: null,
            optionType: null,
            rollChildQtyToParent: false,
            showOnQuote: false,
            additionalDiscount: 0,
            totalProvidedCopies: 0,
            monthlyVolume: null,
            perPageOverageRate: null,
            selectedPerPageRate: 0,
            customPerPageRate: null,
            productCode: "Existing Equipment",
            productServiceType: null,
            isServiceProduct: false,
            leasePrice: 0,
            salesPrice: 0,
            listPrice: 0,
            order: 13,
            lineDetail: null,
            lineDetailForGP: null,
            description: "Existing Equipment",
            hidden: false,
            name: "Existing Equipment",
            picture: null,
            quantity: 1,
            parentId: null,
            groupId: "a0p4U00000FC8CEQA1",
            id: "a0q4U00000PozQzQAJ",
          },
        ],
        documentLastViewed: "2023-03-07T22:16:35.385Z",
        documentViewCount: 8,
        customerNumber: "01-CHICKEN",
        opportunityName:
          "Ian Test for Flow-633988-633988-633988-633988-633988-633988-633988-633988-633988-633988",
        quoteExpirationDate: "2022-08-31",
        quoteNumber: "633988",
        primaryContact: {
          phone: "(801)468-9532",
          email: "iheartchickens@gmail.com",
          name: "Ranger Rusty",
        },
        salesRep: {
          icon: null,
          jobTitle: "Salesforce Architect",
          phone: "(385) 271-3950",
          email: "idoney@lesolsoncompany.com",
          name: "Ian Doney",
          accountId: "001f400000LoPCUAA3",
          accountName: "Steve Foulgers Chickens",
        },
        soldTo: {
          country: "USA",
          zipCode: "84555",
          state: "UT",
          city: "South Salt Lake",
          street: "123 Coop Street",
          name: "Steve Foulgers Chickens",
        },
        isLeaseAmendment: false,
        numSignatures: null,
        totalDiscount: 0,
        showTotalDiscount: true,
        coverPageNeeded: false,
        pricebookId: "01sf4000006lwLvAAI",
        pricebookName: "Z - K12",
        managedITAssessmentNeeded: true,
        showCashPaymentBreakdown: false,
        showLeasePaymentBreakdown: false,
        amendedLeaseTerms: null,
        leaseTerms: "60",
        serviceMinimum: 0,
        serviceBillingFrequency: null,
        showServiceCharges: false,
        equipmentLeaseCompany: "REVCO",
        serviceBillingOption: "Pass Through Lease",
        sourcewellContract: null,
        hpNaspoContractNumbers: null,
        sharpNaspoContractNumbers: null,
        leaseTime: "60",
        purchaseType: "REVCO",
        purchaseOption: "FMV",
        leaseTotal: 401.79,
        additionalNotes: null,
        multipliers:
          "Desktop Support: 0<br>Server Support: 0<br>Advanced Support: 0<br>After Hours Support: 0",
        poNumber: null,
        w9NotNeeded: false,
        quoteTotal: 17318.7,
        id: "a0u4U00000G6LkpQAF",
      
      },
 
  },
  { id: 2, quote: 
    {
      lineItemGroups: [
          {
              deliveryAddress: {
                  zipCode: null,
                  state: null,
                  city: null,
                  street: null
              },
              subtotal: 84611,
              order: 2,
              name: "Print Shop",
              id: "a0p4U00000E3oijQAB"
          },
          {
              deliveryAddress: {
                  zipCode: "69696",
                  state: "UT",
                  city: "South Salt Lake",
                  street: "755 Chapel Dr"
              },
              subtotal: 31265,
              order: 1,
              name: "Main Office",
              id: "a0p4U00000FCTFwQAP"
          }
      ],
      "lineItems": [
          {
              featureCategory: null,
              featureName: null,
              declinedQuantity: null,
              isRejected: false,
              locationRemarks: null,
              optionType: null,
              rollChildQtyToParent: false,
              showOnQuote: true,
              additionalDiscount: 0,
              totalProvidedCopies: 0,
              monthlyVolume: null,
              perPageOverageRate: null,
              selectedPerPageRate: 0,
              customPerPageRate: null,
              productCode: "MX-M6071S",
              productServiceType: null,
              isServiceProduct: false,
              leasePrice: 426.76,
              salesPrice: 18395,
              listPrice: 18395,
              order: 1,
              lineDetail: "Lease Rate Used: .0232",
              lineDetailForGP: "Lease Rate Used: .0232",
              description: "60 pages-per-minute Monochrome Sharp Multi-function System",
              hidden: false,
              name: "MX-M6071S - Sharp Copier #",
              picture: null,
              quantity: 1,
              parentId: null,
              groupId: "a0p4U00000FCTFwQAP",
              id: "a0q4U00000QbRbQQAV"
          },
          {
              featureCategory: "Paper Trays / Drawers",
              featureName: "Drawer / Cabinets / LCC",
              declinedQuantity: null,
              isRejected: false,
              locationRemarks: null,
              optionType: "Component",
              rollChildQtyToParent: false,
              showOnQuote: true,
              additionalDiscount: 0,
              totalProvidedCopies: 0,
              monthlyVolume: null,
              perPageOverageRate: null,
              selectedPerPageRate: 0,
              customPerPageRate: null,
              productCode: "MX-60ABD",
              productServiceType: null,
              isServiceProduct: false,
              leasePrice: 6.15,
              salesPrice: 265,
              listPrice: 265,
              order: 2,
              lineDetail: "Lease Rate Used: .0232",
              lineDetailForGP: "Lease Rate Used: .0232",
              description: "Deluxe Copier Cabinet Base",
              hidden: false,
              name: "MX-60ABD - Sharp Cabinet (M2651-M6071, 2651-6071)",
              picture: null,
              quantity: 1,
              parentId: "a0q4U00000QbRbQQAV",
              groupId: "a0p4U00000FCTFwQAP",
              id: "a0q4U00000QbRbRQAV"
          },
          {
              featureCategory: "Finishing",
              featureName: "Internal",
              declinedQuantity: null,
              isRejected: false,
              locationRemarks: null,
              optionType: "Component",
              rollChildQtyToParent: false,
              showOnQuote: true,
              additionalDiscount: 0,
              totalProvidedCopies: 0,
              monthlyVolume: null,
              perPageOverageRate: null,
              selectedPerPageRate: 0,
              customPerPageRate: null,
              productCode: "MX-TU16",
              productServiceType: null,
              isServiceProduct: false,
              leasePrice: 0,
              salesPrice: 0,
              listPrice: 0,
              order: 3,
              lineDetail: "Lease Rate Used: .0232",
              lineDetailForGP: "Lease Rate Used: .0232",
              description: "Center Exit Tray",
              hidden: false,
              name: "MX-TU16 - Center Exit Tray (M2651-6071)",
              picture: null,
              quantity: 1,
              parentId: "a0q4U00000QbRbQQAV",
              groupId: "a0p4U00000FCTFwQAP",
              id: "a0q4U00000QbRbSQAV",
              services: [
                  {
                      featureCategory: "Service",
                      featureName: "Warranty",
                      declinedQuantity: null,
                      isRejected: false,
                      locationRemarks: null,
                      optionType: "Component",
                      rollChildQtyToParent: false,
                      showOnQuote: true,
                      additionalDiscount: 0,
                      totalProvidedCopies: 0,
                      monthlyVolume: null,
                      perPageOverageRate: null,
                      selectedPerPageRate: 0,
                      customPerPageRate: null,
                      productCode: "Sharp 90 Day Warranty",
                      productServiceType: "Warranty",
                      isServiceProduct: true,
                      leasePrice: 0,
                      salesPrice: 0,
                      listPrice: 0,
                      order: 4,
                      lineDetail: "CPP: 0 (Retail)<br>Overage Rate 0<br>Pages: 0<br>Lease Rate Used: .0232<br>",
                      lineDetailForGP: "CPP: 0 (Retail) Pages: 0 Lease Rate Used: .0232",
                      description: "Sharp Manufacturer Warranty",
                      hidden: false,
                      name: "Sharp 90 Day Warranty",
                      picture: null,
                      quantity: 1,
                      parentId: "a0q4U00000QbRbQQAV",
                      groupId: "a0p4U00000FCTFwQAP",
                      id: "a0q4U00000QbRbTQAV"
                  }
              ],
              isLastWithParent: true
          },
          {
              featureCategory: "Service",
              featureName: "Warranty",
              declinedQuantity: null,
              isRejected: false,
              locationRemarks: null,
              optionType: "Component",
              rollChildQtyToParent: false,
              showOnQuote: true,
              additionalDiscount: 0,
              totalProvidedCopies: 0,
              monthlyVolume: null,
              perPageOverageRate: null,
              selectedPerPageRate: 0,
              customPerPageRate: null,
              productCode: "Sharp 90 Day Warranty",
              productServiceType: "Warranty",
              isServiceProduct: true,
              leasePrice: 0,
              salesPrice: 0,
              listPrice: 0,
              order: 4,
              lineDetail: "CPP: 0 (Retail)<br>Overage Rate 0<br>Pages: 0<br>Lease Rate Used: .0232<br>",
              lineDetailForGP: "CPP: 0 (Retail) Pages: 0 Lease Rate Used: .0232",
              description: "Sharp Manufacturer Warranty",
              hidden: false,
              name: "Sharp 90 Day Warranty",
              picture: null,
              quantity: 1,
              parentId: "a0q4U00000QbRbQQAV",
              groupId: "a0p4U00000FCTFwQAP",
              id: "a0q4U00000QbRbTQAV"
          },
          {
              featureCategory: null,
              featureName: null,
              declinedQuantity: null,
              isRejected: false,
              locationRemarks: null,
              optionType: null,
              rollChildQtyToParent: false,
              showOnQuote: true,
              additionalDiscount: 0,
              totalProvidedCopies: 0,
              monthlyVolume: null,
              perPageOverageRate: null,
              selectedPerPageRate: 0,
              customPerPageRate: null,
              productCode: 'BP-50C26',
              productServiceType: null,
              isServiceProduct: false,
              leasePrice: 218.43,
              salesPrice: 9415,
              listPrice: 9415,
              order: 5,
              lineDetail: "Lease Rate Used: .0232",
              lineDetailForGP: "Lease Rate Used: .0232",
              description: "26 pages-per-minute Color Sharp Multi-function System",
              hidden: false,
              name: "BP-50C26 - Sharp Color Copier #",
              picture: null,
              quantity: 1,
              parentId: null,
              groupId: "a0p4U00000FCTFwQAP",
              id: "a0q4U00000QbRcbQAF"
          },
          {
              featureCategory: "Paper Trays / Drawers",
              featureName: "Drawer / Cabinets / LCC",
              declinedQuantity: null,
              isRejected: false,
              locationRemarks: null,
              optionType: "Component",
              rollChildQtyToParent: false,
              showOnQuote: true,
              additionalDiscount: 0,
              totalProvidedCopies: 0,
              monthlyVolume: null,
              perPageOverageRate: null,
              selectedPerPageRate: 0,
              customPerPageRate: null,
              productCode: "BP-DE12",
              productServiceType: null,
              isServiceProduct: false,
              leasePrice: 22.62,
              salesPrice: 975,
              listPrice: 975,
              order: 6,
              lineDetail: "Lease Rate Used: .0232",
              lineDetailForGP: "Lease Rate Used: .0232",
              description: "Stand/1 X 500 Paper Feed Desk Unit",
              hidden: false,
              name: "BP-DE12 - Stand/1 X 550 Paper Deck (50C26-70M65)#",
              picture: null,
              quantity: 1,
              parentId: "a0q4U00000QbRcbQAF",
              groupId: "a0p4U00000FCTFwQAP",
              id: "a0q4U00000QbRccQAF"
          },
          {
              featureCategory: "Finishing",
              featureName: "Internal",
              declinedQuantity: null,
              isRejected: false,
              locationRemarks: null,
              optionType: "Component",
              rollChildQtyToParent: false,
              showOnQuote: true,
              additionalDiscount: 0,
              totalProvidedCopies: 0,
              monthlyVolume: null,
              perPageOverageRate: null,
              selectedPerPageRate: 0,
              customPerPageRate: null,
              productCode: "BP-FN11",
              productServiceType: null,
              isServiceProduct: false,
              leasePrice: 51.39,
              salesPrice: 2215,
              listPrice: 2215,
              order: 7,
              lineDetail: "Lease Rate Used: .0232",
              lineDetailForGP: "Lease Rate Used: .0232",
              description: "Sharp Finisher (50C26-70C45) #",
              hidden: false,
              name: "BP-FN11 - Finisher (50C26-70M55) #",
              picture: null,
              quantity: 1,
              parentId: "a0q4U00000QbRcbQAF",
              groupId: "a0p4U00000FCTFwQAP",
              id: "a0q4U00000QbRcdQAF",
              services: [
                  {
                      featureCategory: "Service",
                      featureName: "Warranty",
                      declinedQuantity: null,
                      isRejected: false,
                      locationRemarks: null,
                      optionType: "Component",
                      rollChildQtyToParent: false,
                      showOnQuote: true,
                      additionalDiscount: 0,
                      totalProvidedCopies: 0,
                      monthlyVolume: null,
                      perPageOverageRate: null,
                      selectedPerPageRate: 0,
                      customPerPageRate: null,
                      productCode: "Sharp 90 Day Warranty",
                      productServiceType: "Warranty",
                      isServiceProduct: true,
                      leasePrice: 0,
                      salesPrice: 0,
                      listPrice: 0,
                      order: 8,
                      lineDetail: "CPP: 0 (Retail)<br>Overage Rate 0<br>Pages: 0<br>Lease Rate Used: .0232<br>",
                      lineDetailForGP: "CPP: 0 (Retail) Pages: 0 Lease Rate Used: .0232",
                      description: "Sharp Manufacturer Warranty",
                      hidden: false,
                      name: "Sharp 90 Day Warranty",
                      picture: null,
                      quantity: 1,
                      parentId: "a0q4U00000QbRcbQAF",
                      groupId: "a0p4U00000FCTFwQAP",
                      id: "a0q4U00000QbRceQAF"
                  }
              ],
              isLastWithParent: true
          },
          {
              featureCategory: "Service",
              featureName: "Warranty",
              declinedQuantity: null,
              isRejected: false,
              locationRemarks: null,
              optionType: "Component",
              rollChildQtyToParent: false,
              showOnQuote: true,
              additionalDiscount: 0,
              totalProvidedCopies: 0,
              monthlyVolume: null,
              perPageOverageRate: null,
              selectedPerPageRate: 0,
              customPerPageRate: null,
              productCode: "Sharp 90 Day Warranty",
              productServiceType: "Warranty",
              isServiceProduct: true,
              leasePrice: 0,
              salesPrice: 0,
              listPrice: 0,
              order: 8,
              lineDetail: "CPP: 0 (Retail)<br>Overage Rate 0<br>Pages: 0<br>Lease Rate Used: .0232<br>",
              lineDetailForGP: "CPP: 0 (Retail) Pages: 0 Lease Rate Used: .0232",
              description: "Sharp Manufacturer Warranty",
              hidden: false,
              name: "Sharp 90 Day Warranty",
              picture: null,
              quantity: 1,
              parentId: "a0q4U00000QbRcbQAF",
              groupId: "a0p4U00000FCTFwQAP",
              id: "a0q4U00000QbRceQAF"
          },
          {
              featureCategory: null,
              featureName: null,
              declinedQuantity: null,
              isRejected: false,
              locationRemarks: null,
              optionType: null,
              rollChildQtyToParent: false,
              showOnQuote: true,
              additionalDiscount: 0,
              totalProvidedCopies: 0,
              monthlyVolume: null,
              perPageOverageRate: null,
              selectedPerPageRate: 0,
              customPerPageRate: null,
              productCode: "RI-409393",
              productServiceType: null,
              isServiceProduct: false,
              leasePrice: 1962.98,
              salesPrice: 84611,
              listPrice: 84611,
              order: 9,
              lineDetail: null,
              lineDetailForGP: null,
              description: "Ricoh Pro C5310s",
              hidden: false,
              name: "Ricoh Pro C5310s",
              picture: null,
              quantity: 1,
              parentId: null,
              groupId: "a0p4U00000E3oijQAB",
              id: "a0q4U00000QbYQ5QAN",
              services: [],
              isLastWithParent: true
          },
          {
              featureCategory: "Paper_Sources",
              featureName: "Paper Desks & Trays",
              declinedQuantity: null,
              isRejected: false,
              locationRemarks: null,
              optionType: "Component",
              rollChildQtyToParent: false,
              showOnQuote: false,
              additionalDiscount: 0,
              totalProvidedCopies: 0,
              monthlyVolume: null,
              perPageOverageRate: null,
              selectedPerPageRate: 0,
              customPerPageRate: null,
              productCode: "Ricoh C53xx Start Up Bundle",
              productServiceType: null,
              isServiceProduct: false,
              leasePrice: 0,
              salesPrice: 0,
              listPrice: 0,
              order: 10,
              lineDetail: null,
              lineDetailForGP: null,
              description: "Ricoh C53xx Start Up Bundle",
              hidden: false,
              name: "Ricoh C53xx Start Up Bundle",
              picture: null,
              quantity: 1,
              parentId: "a0q4U00000QbYQ5QAN",
              groupId: "a0p4U00000E3oijQAB",
              id: "a0q4U00000QbYQ6QAN"
          },
          {
              featureCategory: "Start Up Bundles",
              featureName: "Start Up Bundles - Required",
              declinedQuantity: null,
              isRejected: false,
              locationRemarks: null,
              optionType: "Component",
              rollChildQtyToParent: false,
              showOnQuote: false,
              additionalDiscount: 0,
              totalProvidedCopies: 0,
              monthlyVolume: null,
              perPageOverageRate: null,
              selectedPerPageRate: 0,
              customPerPageRate: null,
              productCode: "Phoenix Advanced B/W Retail Start Up Bundle",
              productServiceType: null,
              isServiceProduct: false,
              leasePrice: 0,
              salesPrice: 0,
              listPrice: 0,
              order: 3000,
              lineDetail: null,
              lineDetailForGP: null,
              description: "Phoenix Advanced B/W Retail Start Up Bundle",
              hidden: false,
              name: "Phoenix Advanced B/W Retail Start Up Bundle",
              picture: null,
              quantity: 1,
              parentId: "a0q4U00000QbRbQQAV",
              groupId: "a0p4U00000FCTFwQAP",
              id: "a0q4U00000QbRbUQAV"
          },
          {
              featureCategory: "Start Up Bundles",
              featureName: "Start Up Bundles - Required",
              declinedQuantity: null,
              isRejected: false,
              locationRemarks: null,
              optionType: "Component",
              rollChildQtyToParent: false,
              showOnQuote: false,
              additionalDiscount: 0,
              totalProvidedCopies: 0,
              monthlyVolume: null,
              perPageOverageRate: null,
              selectedPerPageRate: 0,
              customPerPageRate: null,
              productCode: "Atlas/Titan Startup Bundle",
              productServiceType: null,
              isServiceProduct: false,
              leasePrice: 0,
              salesPrice: 0,
              listPrice: 0,
              order: 3001,
              lineDetail: null,
              lineDetailForGP: null,
              description: "Atlas/Titan Startup Bundle",
              hidden: false,
              name: "Atlas/Titan Startup Bundle",
              picture: null,
              quantity: 1,
              parentId: "a0q4U00000QbRcbQAF",
              groupId: "a0p4U00000FCTFwQAP",
              id: "a0q4U00000QbRcfQAF"
          },
          {
              featureCategory: null,
              featureName: null,
              declinedQuantity: null,
              isRejected: false,
              locationRemarks: null,
              optionType: "Component",
              rollChildQtyToParent: false,
              showOnQuote: false,
              additionalDiscount: 0,
              totalProvidedCopies: 0,
              monthlyVolume: null,
              perPageOverageRate: null,
              selectedPerPageRate: 0,
              customPerPageRate: null,
              productCode: "MX-561NT",
              productServiceType: null,
              isServiceProduct: false,
              leasePrice: 0,
              salesPrice: 0,
              listPrice: 132,
              order: 3002,
              lineDetail: null,
              lineDetailForGP: null,
              description: "Sharp Toner",
              hidden: false,
              name: "Sharp Toner",
              picture: null,
              quantity: 1,
              parentId: "a0q4U00000QbRbQQAV",
              groupId: "a0p4U00000FCTFwQAP",
              id: "a0q4U00000QbRbVQAV"
          },
          {
              featureCategory: null,
              featureName: null,
              declinedQuantity: null,
              isRejected: false,
              locationRemarks: null,
              optionType: "Component",
              rollChildQtyToParent: false,
              showOnQuote: false,
              additionalDiscount: 0,
              totalProvidedCopies: 0,
              monthlyVolume: null,
              perPageOverageRate: null,
              selectedPerPageRate: 0,
              customPerPageRate: null,
              productCode: "MX-561NV",
              productServiceType: null,
              isServiceProduct: false,
              leasePrice: 0,
              salesPrice: 0,
              listPrice: 190,
              order: 3003,
              lineDetail: null,
              lineDetailForGP: null,
              description: "Sharp Developer",
              hidden: false,
              name: "Sharp Developer",
              picture: null,
              quantity: 1,
              parentId: "a0q4U00000QbRbQQAV",
              groupId: "a0p4U00000FCTFwQAP",
              id: "a0q4U00000QbRbWQAV"
          },
          {
              featureCategory: null,
              featureName: null,
              declinedQuantity: null,
              isRejected: false,
              locationRemarks: null,
              optionType: "Component",
              rollChildQtyToParent: false,
              showOnQuote: false,
              additionalDiscount: 0,
              totalProvidedCopies: 0,
              monthlyVolume: null,
              perPageOverageRate: null,
              selectedPerPageRate: 0,
              customPerPageRate: null,
              productCode: "SURGE-15",
              productServiceType: null,
              isServiceProduct: false,
              leasePrice: 0,
              salesPrice: 0,
              listPrice: 180,
              order: 3004,
              lineDetail: null,
              lineDetailForGP: null,
              description: "15 Amp Surge Suppressor",
              hidden: false,
              name: "15 Amp Surge Suppressor",
              picture: null,
              quantity: 1,
              parentId: "a0q4U00000QbRbQQAV",
              groupId: "a0p4U00000FCTFwQAP",
              id: "a0q4U00000QbRbXQAV"
          },
          {
              featureCategory: null,
              featureName: null,
              declinedQuantity: null,
              isRejected: false,
              locationRemarks: null,
              optionType: "Component",
              rollChildQtyToParent: false,
              showOnQuote: false,
              additionalDiscount: 0,
              totalProvidedCopies: 0,
              monthlyVolume: null,
              perPageOverageRate: null,
              selectedPerPageRate: 0,
              customPerPageRate: null,
              productCode: "BP-NT70BA",
              productServiceType: null,
              isServiceProduct: false,
              leasePrice: 0,
              salesPrice: 0,
              listPrice: 130,
              order: 3005,
              lineDetail: null,
              lineDetailForGP: null,
              description: "Sharp Toner - Black",
              hidden: false,
              name: "Sharp Toner - Black",
              picture: null,
              quantity: 1,
              parentId: "a0q4U00000QbRcbQAF",
              groupId: "a0p4U00000FCTFwQAP",
              id: "a0q4U00000QbRcgQAF"
          },
          {
              featureCategory: null,
              featureName: null,
              declinedQuantity: null,
              isRejected: false,
              locationRemarks: null,
              optionType: "Component",
              rollChildQtyToParent: false,
              showOnQuote: false,
              additionalDiscount: 0,
              totalProvidedCopies: 0,
              monthlyVolume: null,
              perPageOverageRate: null,
              selectedPerPageRate: 0,
              customPerPageRate: null,
              productCode: "BP-NT70CA",
              productServiceType: null,
              isServiceProduct: false,
              leasePrice: 0,
              salesPrice: 0,
              listPrice: 277,
              order: 3006,
              lineDetail: null,
              lineDetailForGP: null,
              description: "Sharp Toner - Cyan",
              hidden: false,
              name: "Sharp Toner - Cyan",
              picture: null,
              quantity: 1,
              parentId: "a0q4U00000QbRcbQAF",
              groupId: "a0p4U00000FCTFwQAP",
              id: "a0q4U00000QbRchQAF"
          },
          {
              featureCategory: null,
              featureName: null,
              declinedQuantity: null,
              isRejected: false,
              locationRemarks: null,
              optionType: "Component",
              rollChildQtyToParent: false,
              showOnQuote: false,
              additionalDiscount: 0,
              totalProvidedCopies: 0,
              monthlyVolume: null,
              perPageOverageRate: null,
              selectedPerPageRate: 0,
              customPerPageRate: null,
              productCode: "BP-NT70MA",
              productServiceType: null,
              isServiceProduct: false,
              leasePrice: 0,
              salesPrice: 0,
              listPrice: 277,
              order: 3007,
              lineDetail: null,
              lineDetailForGP: null,
              description: "Sharp Toner - Magenta",
              hidden: false,
              name: "Sharp Toner - Magenta",
              picture: null,
              quantity: 1,
              parentId: "a0q4U00000QbRcbQAF",
              groupId: "a0p4U00000FCTFwQAP",
              id: "a0q4U00000QbRciQAF"
          },
          {
              featureCategory: null,
              featureName: null,
              declinedQuantity: null,
              isRejected: false,
              locationRemarks: null,
              optionType: "Component",
              rollChildQtyToParent: false,
              showOnQuote: false,
              additionalDiscount: 0,
              totalProvidedCopies: 0,
              monthlyVolume: null,
              perPageOverageRate: null,
              selectedPerPageRate: 0,
              customPerPageRate: null,
              productCode: "BP-NT70YA",
              productServiceType: null,
              isServiceProduct: false,
              leasePrice: 0,
              salesPrice: 0,
              listPrice: 277,
              order: 3008,
              lineDetail: null,
              lineDetailForGP: null,
              description: "Sharp Toner - Yellow",
              hidden: false,
              name: "Sharp Toner - Yellow",
              picture: null,
              quantity: 1,
              parentId: "a0q4U00000QbRcbQAF",
              groupId: "a0p4U00000FCTFwQAP",
              id: "a0q4U00000QbRcjQAF"
          },
          {
              featureCategory: null,
              featureName: null,
              declinedQuantity: null,
              isRejected: false,
              locationRemarks: null,
              optionType: "Component",
              rollChildQtyToParent: false,
              showOnQuote: false,
              additionalDiscount: 0,
              totalProvidedCopies: 0,
              monthlyVolume: null,
              perPageOverageRate: null,
              selectedPerPageRate: 0,
              customPerPageRate: null,
              productCode: "SURGE-15",
              productServiceType: null,
              isServiceProduct: false,
              leasePrice: 0,
              salesPrice: 0,
              listPrice: 180,
              order: 3009,
              lineDetail: null,
              lineDetailForGP: null,
              description: "15 Amp Surge Suppressor",
              hidden: false,
              name: "15 Amp Surge Suppressor",
              picture: null,
              quantity: 1,
              parentId: "a0q4U00000QbRcbQAF",
              groupId: "a0p4U00000FCTFwQAP",
              id: "a0q4U00000QbRckQAF"
          },
          {
              featureCategory: null,
              featureName: null,
              declinedQuantity: null,
              isRejected: false,
              locationRemarks: null,
              optionType: "Component",
              rollChildQtyToParent: false,
              showOnQuote: false,
              additionalDiscount: 0,
              totalProvidedCopies: 0,
              monthlyVolume: null,
              perPageOverageRate: null,
              selectedPerPageRate: 0,
              customPerPageRate: null,
              productCode: 828597,
              productServiceType: null,
              isServiceProduct: false,
              leasePrice: 0,
              salesPrice: 0,
              listPrice: 0,
              order: 3010,
              lineDetail: null,
              lineDetailForGP: null,
              description: null,
              hidden: false,
              name: "Ricoh - Pro C5300 - Black Toner",
              picture: null,
              quantity: 1,
              parentId: "a0q4U00000QbYQ5QAN",
              groupId: "a0p4U00000E3oijQAB",
              id: "a0q4U00000QbYQ7QAN"
          },
          {
              featureCategory: null,
              featureName: null,
              declinedQuantity: null,
              isRejected: false,
              locationRemarks: null,
              optionType: "Component",
              rollChildQtyToParent: false,
              showOnQuote: false,
              additionalDiscount: 0,
              totalProvidedCopies: 0,
              monthlyVolume: null,
              perPageOverageRate: null,
              selectedPerPageRate: 0,
              customPerPageRate: null,
              productCode: 828600,
              productServiceType: null,
              isServiceProduct: false,
              leasePrice: 0,
              salesPrice: 0,
              listPrice: 0,
              order: 3011,
              lineDetail: null,
              lineDetailForGP: null,
              description: null,
              hidden: false,
              name: "Ricoh - Pro C5300 - Cyan Toner",
              picture: null,
              quantity: 1,
              parentId: "a0q4U00000QbYQ5QAN",
              groupId: "a0p4U00000E3oijQAB",
              id: "a0q4U00000QbYQ8QAN"
          },
          {
              featureCategory: null,
              featureName: null,
              declinedQuantity: null,
              isRejected: false,
              locationRemarks: null,
              optionType: "Component",
              rollChildQtyToParent: false,
              showOnQuote: false,
              additionalDiscount: 0,
              totalProvidedCopies: 0,
              monthlyVolume: null,
              perPageOverageRate: null,
              selectedPerPageRate: 0,
              customPerPageRate: null,
              productCode: "SURGE-220",
              productServiceType: null,
              isServiceProduct: false,
              leasePrice: 0,
              salesPrice: 0,
              listPrice: 0,
              order: 3012,
              lineDetail: null,
              lineDetailForGP: null,
              description: "208/20 Amp Surge Suppressor",
              hidden: false,
              name: "208/20 Amp Surge Suppressor",
              picture: null,
              quantity: 1,
              parentId: "a0q4U00000QbYQ5QAN",
              groupId: "a0p4U00000E3oijQAB",
              id: "a0q4U00000QbYQ9QAN"
          }
      ],
      documentLastViewed: "2023-03-30T15:54:22.902Z",
      documentViewCount: 3,
      customerNumber: "01-CHICKEN",
      opportunityName: "Get Lease Docs Signed Test-637137",
      quoteExpirationDate: 2022-12-31,
      quoteNumber: 637137,
      primaryContact: {
          phone: 8014689532,
          email: null,
          name: "Ranger Rusty"
      },
      salesRep: {
          icon: null,
          jobTitle: "Salesforce Architect",
          phone: "(385) 271-3950",
          email: "idoney@lesolsoncompany.com",
          name: "Ian Doney",
          accountId: "001f400000LoPCUAA3",
          accountName: "Steve Foulgers Chickens"
      },
      soldTo: {
          country: null,
          zipCode: 69696,
          state: "UT",
          city: "South Salt Lake",
          street: "755 Chapel Dr",
          name: "Steve Foulgers Chickens"
      },
      isLeaseAmendment: false,
      numSignatures: null,
      totalDiscount: 0,
      showTotalDiscount: false,
      coverPageNeeded: false,
      pricebookId: "01sf4000001rea8AAA",
      pricebookName: "Standard Price Book",
      managedITAssessmentNeeded: false,
      showCashPaymentBreakdown: false,
      showLeasePaymentBreakdown: false,
      amendedLeaseTerms: null,
      leaseTerms: 60,
      serviceMinimum: null,
      serviceBillingFrequency: null,
      showServiceCharges: false,
      equipmentLeaseCompany: "REVCO",
      serviceBillingOption: null,
      sourcewellContract: null,
      hpNaspoContractNumbers: null,
      sharpNaspoContractNumbers: null,
      leaseTime: 60,
      purchaseType: "REVCO",
      purchaseOption: "FMV",
      leaseTotal: 2688.33,
      additionalNotes: null,
      multipliers: "Desktop Support: 0<br>Server Support: 0<br>Advanced Support: 0<br>After Hours Support: 0",
      poNumber: null,
      w9NotNeeded: false,
      quoteTotal: 115876,
      id: "a0u4U00000Kius3QAB",
      declinedItems: []
  }
  }
];

// Define a route that takes an ID parameter and looks up the corresponding data

app.get("/data/:id", (req, res) => {
  const id = parseInt(req.params.id);
  const result = data.find((d) => d.id === id);
  if (result) {
    res.send(result);
  } else {
    res.status(404).send("Data not found");
  }
});

app.listen(3000, () => {
  console.log("Server started on port 3000");
});
